Created items schema
scalableinternetservices/swap-space pull request #8
Opened 2019-10-18 20:13 UTC by DonLe27

Created and linked items to users.

2019-10-18 20:14 UTC, cheimu approved these changes

2019-10-25 02:52 UTC, GalenWong requested changes

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/app/controllers/items_controller.rb
> +      params.require(:item).permit(:category, :name, :user_id, :date_added)
We don't really need `:date_added` since when the row is created, a `created_at` field is automatically attached to the row.

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/app/views/items/_form.html.erb
> +  </div>
We should remove this field. See comment above.

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/app/views/items/index.html.erb
> +        <td><%= item.date_added %></td>
we wanna use `created_at` instead.

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/app/views/items/_item.json.jbuilder
> +json.extract! item, :id, :category, :name, :user_id, :date_added, :created_at, :updated_at
remove `:date_added`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/app/views/items/show.html.erb
> +  <%= @item.date_added %>
same here. use `created_at`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/db/migrate/20191018200306_create_items.rb
> +      t.timestamp :date_added
remove `date_added` field.

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/db/schema.rb
> +    t.datetime "date_added"
remove `date_added`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/test/controllers/items_controller_test.rb
> +      post items_url, params: { item: { category: @item.category, date_added: @item.date_added, name: @item.name, user_id: @item.user_id } }
No `date_added`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/test/controllers/items_controller_test.rb
> +    patch item_url(@item), params: { item: { category: @item.category, date_added: @item.date_added, name: @item.name, user_id: @item.user_id } }
no `date_added`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/test/fixtures/items.yml
> +  date_added: 2019-10-18 13:03:06
remove `date_added`

2019-10-25 02:52 UTC, GalenWong commented on environment/swapspace/test/fixtures/items.yml
> +  date_added: 2019-10-18 13:03:06
remove `date_added`

2019-10-25 02:58 UTC, GalenWong commented on environment/swapspace/app/views/items/_form.html.erb
> +  </div>
this should be whoever the current logined user.

2019-10-25 19:26 UTC, merged